name: 'SRC DataLinter'
description: 'Lint SRC Data'
inputs:
  files:
    description: 'Lint target'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "##[add-matcher]${{ github.action_path }}/src-lint.json"
      shell: bash
#     - run: chmod +x ${{ github.action_path }}/bin/SRCDataLinter.exe
#       shell: bash
    - run: ls -lar ${{ github.action_path }}/bin/
      shell: bash
    - run: dotnet ${{ github.action_path }}/bin/SRCDataLinter.dll ${{ inputs.files }}
      shell: bash
