name: 'SRC DataLinter'
description: 'Lint SRC Data'
inputs:
  files:
    description: 'Lint target file or directory.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
